### ISSUE TITLE
Exception on Creating New Inventory

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#1038]
Getting this in my dev env, after blowing away all my tables, and then creating a new inventory with simply `forseti inventory create`.

Although the crawler is able to continue, the server doesn't seem to return or completes.

```
ERROR:root:Exception iterating responses: '2018-02-02T01:14:09.62189' has type str, but expected one of: int, long
Traceback (most recent call last):
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/grpc/_server.py", line 403, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "/usr/local/google/home/henryc/git/forseti-security/google/cloud/forseti/services/utils.py", line 44, in wrapper
    for result in f(*args):
  File "/usr/local/google/home/henryc/git/forseti-security/google/cloud/forseti/services/inventory/service.py", line 86, in Create
    last_error=repr(progress.last_error))
TypeError: '2018-02-02T01:14:09.62189' has type str, but expected one of: int, long
```

**Comment by jiyunyao** [comment]
Stoped the server, reinstall and it should be good. This is because the proto hasn't been rebuilt on your system.

**Comment by blueandgold** [comment]
Cool, that fixed it, thanks~!
