### ISSUE TITLE
Unable to install rc2

### ISSUE THREAD

**Issue by antoine-castex** [GoogleCloudPlatform/forseti-security#1467]
Since yesterday, after download the rc2 , unable to install

Traceback (most recent call last):
  File "setup/installer.py", line 23, in <module>
    run_forseti_installer.run()
  File "/home/antoine_castex/forseti-security/setup/gcp/run_forseti_installer.py", line 114, in run
    instructions = forseti_server.run_setup(final_setup=False)
  File "/home/antoine_castex/forseti-security/setup/gcp/installer/forseti_installer.py", line 131, in run_setup
    deployment_tpl_path) = self.create_resource_files()
  File "/home/antoine_castex/forseti-security/setup/gcp/installer/forseti_installer.py", line 160, in create_resource_files
    conf_file_path = self.generate_forseti_conf()
  File "/home/antoine_castex/forseti-security/setup/gcp/installer/forseti_server_installer.py", line 222, in generate_forseti_conf
    ForsetiServerInstaller, self).generate_forseti_conf()
  File "/home/antoine_castex/forseti-security/setup/gcp/installer/forseti_installer.py", line 359, in generate_forseti_conf
    self.config.timestamp)
  File "/home/antoine_castex/forseti-security/setup/gcp/installer/util/files.py", line 107, in generate_forseti_conf
    conf_values):
  File "/home/antoine_castex/forseti-security/setup/gcp/installer/util/files.py", line 150, in generate_file_from_template
    out_contents = tmpl_contents.format(**template_values)
KeyError: 'INV_SUMMARY_BUCKET'

Need to replace the variable by a fixed value ....

**Comment by blueandgold** [comment]
Hi Anotine, this was fixed in PR #1471 for RC2.  Can you please try again?  I'm going to close this issue, but please feel free to follow-up if you still have questions.  Thanks!
