### ISSUE TITLE
Pylint auto-install fails?

### ISSUE THREAD

**Issue by MartenvanWezel** [GoogleCloudPlatform/forseti-security#1472]
Empty project. Start Cloud Shell.

```
admin_@forseti-195214:~$ git clone --single-branch -b 2.0-rc2 https://github.com/GoogleCloudPlatform/forseti-security.git
Cloning into 'forseti-security'...
remote: Counting objects: 16129, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 16129 (delta 79), reused 68 (delta 62), pack-reused 16006
Receiving objects: 100% (16129/16129), 20.73 MiB | 7.37 MiB/s, done.
Resolving deltas: 100% (10995/10995), done.
admin_@forseti-195214:~$ cd forseti-security
admin_@forseti-195214:~/forseti-security$ python setup.py
warning: no files found matching '*.jpg' under directory 'doc'
warning: no files found matching '*.mako' under directory 'doc'
warning: no files found matching 'distribute_setup.py'
warning: no files found matching 'sa2to3.py'
warning: no files found matching 'ez_setup.py'
no previously-included directories found matching 'doc/build/output'
zip_safe flag not set; analyzing archive contents...
Installed /home/admin_/forseti-security/.eggs/SQLAlchemy-1.2.7-py2.7-linux-x86_64.egg
Searching for pylint-quotes
Reading https://pypi.python.org/simple/pylint-quotes/
Downloading https://files.pythonhosted.org/packages/ba/20/4e59a01fd90fbe67385b790cb6ddb4a462f4d8e15548bab27c59c3b23fd3/pylint-quotes-0.1.9.tar.gz#sha256=f319b6a8692e799363a986504836d
ad09178cbfcd3bf03b33562693b39e27226
Best match: pylint-quotes 0.1.9
Extracting pylint_quotes-0.1.9-py2.7.egg to /home/admin_/forseti-security/.eggs
Processing pylint-quotes-0.1.9.tar.gz
Writing /tmp/easy_install-h6ZSwN/pylint-quotes-0.1.9/setup.cfg
Running pylint-quotes-0.1.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-h6ZSwN/pylint-quotes-0.1.9/egg-dist-tmp-Kvvdsz
creating /home/admin_/forseti-security/.eggs/pylint_quotes-0.1.9-py2.7.egg
Extracting pylint_quotes-0.1.9-py2.7.egg to /home/admin_/forseti-security/.eggs

Installed /home/admin_/forseti-security/.eggs/pylint_quotes-0.1.9-py2.7.egg
Searching for pylint
Downloading https://files.pythonhosted.org/packages/ba/20/4e59a01fd90fbe67385b790cb6ddb4a462f4d8e15548bab27c59c3b23fd3/pylint-quotes-0.1.9.tar.gz#sha256=f319b6a8692e799363a986504836dad09178cbfcd3bf03b33562693b39e27226
Best match: pylint quotes-0.1.9
Processing pylint-quotes-0.1.9.tar.gz
Writing /tmp/easy_install-I9HIWq/pylint-quotes-0.1.9/setup.cfg
Running pylint-quotes-0.1.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-I9HIWq/pylint-quotes-0.1.9/egg-dist-tmp-BQ9BKL
removing '/home/admin_/forseti-security/.eggs/pylint_quotes-0.1.9-py2.7.egg' (and everything under it)
creating /home/admin_/forseti-security/.eggs/pylint_quotes-0.1.9-py2.7.egg
Extracting pylint_quotes-0.1.9-py2.7.egg to /home/admin_/forseti-security/.eggs

Installed /home/admin_/forseti-security/.eggs/pylint_quotes-0.1.9-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 145, in <module>
    zip_safe=False,   # Set to False: apputils doesn't like zip_safe eggs
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 317, in __init__
    self.fetch_build_eggs(attrs['setup_requires'])
  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 372, in fetch_build_eggs
    replace_conflicting=True,
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pylint' distribution was not found and is required by the application
```

Guess I'll manually install:

```
admin_@forseti-195214:~/forseti-security$ sudo apt-get install pylint
TERM: screen
********************************************************************************
You are running apt-get tool inside of Cloud Shell. Note that your Cloud Shell
machine is ephemeral and will be reset once you are not using it interactively
for about half an hour.  No system-wide change will persist beyond that.
Note that your home directory does persist across VM instantiations, so consider
installing your tools into your home directory whenever possible.
To suppress this warning, create an empty ~/.cloudshell/no-apt-get-warning file.
The command will automatically proceed in 5 seconds or on any key.
Visit https://cloud.google.com/shell/help for more information.
********************************************************************************
Reading package lists... Done
install/pylint: Handling install for emacsen flavor emacs24
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libgoogle-perftools4 libtcmalloc-minimal4
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  blt libtk8.6 libxss1 python-astroid python-backports.functools-lru-cache python-isort python-lazy-object-proxy python-six python-tk python-wrapt tk8.6-blt2.5
Suggested packages:
  blt-demo tk8.6 pylint-doc python-mccabe tix python-tk-dbg
The following NEW packages will be installed:
  blt libtk8.6 libxss1 pylint python-astroid python-backports.functools-lru-cache python-isort python-lazy-object-proxy python-six python-tk python-wrapt tk8.6-blt2.5
0 upgraded, 12 newly installed, 0 to remove and 28 not upgraded.
Need to get 1,807 kB of archives.
After this operation, 6,583 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://gce_debian_mirror.storage.googleapis.com jessie/main amd64 libxss1 amd64 1:1.2.2-1 [17.5 kB]
Get:2 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 libtk8.6 amd64 8.6.6-1+b1 [754 kB]
Get:3 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 tk8.6-blt2.5 amd64 2.5.3+dfsg-3 [585 kB]
Get:4 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 blt amd64 2.5.3+dfsg-3 [14.6 kB]
Get:5 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 python-lazy-object-proxy amd64 1.2.2-1 [20.7 kB]
Get:6 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 python-six all 1.10.0-3 [14.4 kB]
Get:7 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 python-wrapt amd64 1.9.0-2 [31.5 kB]
Get:8 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 python-astroid all 1.4.9-1 [89.8 kB]
Get:9 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 python-isort all 4.2.5+ds1-2 [37.8 kB]
Get:10 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 python-backports.functools-lru-cache all 1.3-1 [5,912 B]
Get:11 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 pylint all 1.6.5-1 [208 kB]
Get:12 http://gce_debian_mirror.storage.googleapis.com stretch/main amd64 python-tk amd64 2.7.13-1 [27.4 kB]
Fetched 1,807 kB in 2s (642 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libxss1:amd64.
(Reading database ... 43066 files and directories currently installed.)
Preparing to unpack .../00-libxss1_1%3a1.2.2-1_amd64.deb ...
Unpacking libxss1:amd64 (1:1.2.2-1) ...
Selecting previously unselected package libtk8.6:amd64.
Preparing to unpack .../01-libtk8.6_8.6.6-1+b1_amd64.deb ...
Unpacking libtk8.6:amd64 (8.6.6-1+b1) ...
Selecting previously unselected package tk8.6-blt2.5.
Preparing to unpack .../02-tk8.6-blt2.5_2.5.3+dfsg-3_amd64.deb ...
Unpacking tk8.6-blt2.5 (2.5.3+dfsg-3) ...
Selecting previously unselected package blt.
Preparing to unpack .../03-blt_2.5.3+dfsg-3_amd64.deb ...
Unpacking blt (2.5.3+dfsg-3) ...
Selecting previously unselected package python-lazy-object-proxy.
Preparing to unpack .../04-python-lazy-object-proxy_1.2.2-1_amd64.deb ...
Unpacking python-lazy-object-proxy (1.2.2-1) ...
Selecting previously unselected package python-six.
Preparing to unpack .../05-python-six_1.10.0-3_all.deb ...
Unpacking python-six (1.10.0-3) ...
Selecting previously unselected package python-wrapt.
Preparing to unpack .../06-python-wrapt_1.9.0-2_amd64.deb ...
Unpacking python-wrapt (1.9.0-2) ...
Selecting previously unselected package python-astroid.
Preparing to unpack .../07-python-astroid_1.4.9-1_all.deb ...
Unpacking python-astroid (1.4.9-1) ...
Selecting previously unselected package python-isort.
Preparing to unpack .../08-python-isort_4.2.5+ds1-2_all.deb ...
Unpacking python-isort (4.2.5+ds1-2) ...
Selecting previously unselected package python-backports.functools-lru-cache.
Preparing to unpack .../09-python-backports.functools-lru-cache_1.3-1_all.deb ...
Unpacking python-backports.functools-lru-cache (1.3-1) ...
Selecting previously unselected package pylint.
Preparing to unpack .../10-pylint_1.6.5-1_all.deb ...
Unpacking pylint (1.6.5-1) ...
Selecting previously unselected package python-tk.
Preparing to unpack .../11-python-tk_2.7.13-1_amd64.deb ...
Unpacking python-tk (2.7.13-1) ...
Setting up python-isort (4.2.5+ds1-2) ...
Setting up python-lazy-object-proxy (1.2.2-1) ...
Setting up python-backports.functools-lru-cache (1.3-1) ...
Setting up libxss1:amd64 (1:1.2.2-1) ...
Setting up python-six (1.10.0-3) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up python-wrapt (1.9.0-2) ...
Setting up libtk8.6:amd64 (8.6.6-1+b1) ...
Setting up tk8.6-blt2.5 (2.5.3+dfsg-3) ...
Setting up python-astroid (1.4.9-1) ...
Setting up blt (2.5.3+dfsg-3) ...
Setting up pylint (1.6.5-1) ...
Install pylint for emacs24
install/pylint: Handling install for emacsen flavor emacs24
Wrote /usr/share/emacs24/site-lisp/pylint/pylint.elc
Setting up python-tk (2.7.13-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
```

And then it works... ish. See second issue. (TL;DR: it tries to also auto-install mysql and fails?)

**Comment by MartenvanWezel** [comment]
Figured it out, read install instructions poorly. (need to run python setup/installer.py not python setup.py
