### ISSUE TITLE
Inventory module should implement the same logic to disable notification (should_notify parameter) as the notified module.

### ISSUE THREAD

**Issue by abdelsource** [GoogleCloudPlatform/forseti-security#1661]
The Inventory modules try to send emails after a fresh install if the sample config file in github is used. If not EMAIL_RECIPIENT is provided the script fails after inventory is finished with error 

2018-06-10 22:54:35,648 __main__     INFO     _complete_snapshot_cycle Inventory load cycle completed with SUCCESS: 20180610T205234Z
Traceback (most recent call last):
  File "/home/abdelfettah/.virtualenvs/forseti-security/lib/python2.7/site-packages/forseti_security-1.1.11-py2.7.egg/google/cloud/security/inventory/inventory_loader.py", line 379, in <module>
    app.run()
  File "/home/abdelfettah/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/home/abdelfettah/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/home/abdelfettah/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/home/abdelfettah/.virtualenvs/forseti-security/lib/python2.7/site-packages/forseti_security-1.1.11-py2.7.egg/google/cloud/security/inventory/inventory_loader.py", line 375, in main
    notifier.process(message)
  File "/home/abdelfettah/.virtualenvs/forseti-security/lib/python2.7/site-packages/forseti_security-1.1.11-py2.7.egg/google/cloud/security/notifier/notifier.py", line 136, in process
    payload.get('email_recipient')
  File "/home/abdelfettah/.virtualenvs/forseti-security/lib/python2.7/site-packages/forseti_security-1.1.11-py2.7.egg/google/cloud/security/notifier/pipelines/email_inventory_snapshot_summary_pipeline.py", line 113, in run
    self._send(email_sender, email_recipient, email_subject, email_content)
  File "/home/abdelfettah/.virtualenvs/forseti-security/lib/python2.7/site-packages/forseti_security-1.1.11-py2.7.egg/google/cloud/security/notifier/pipelines/email_inventory_snapshot_summary_pipeline.py", line 91, in _send
    attachment=attachment)
  File "/home/abdelfettah/.virtualenvs/forseti-security/lib/python2.7/site-packages/forseti_security-1.1.11-py2.7.egg/google/cloud/security/common/util/email_util.py", line 112, in send
    email = self._add_recipients(email, email_recipient)
  File "/home/abdelfettah/.virtualenvs/forseti-security/lib/python2.7/site-packages/forseti_security-1.1.11-py2.7.egg/google/cloud/security/common/util/email_util.py", line 74, in _add_recipients
    recipients = email_recipients.split(',')

A suggested way to fix this is adding a should_notify to the global section of the config file and setting it to false in the sample config file.

**Comment by jjawad-google** [comment]
This is fixed in 2.0. Try updating and if the problem persists, please open a new issue.
