### ISSUE TITLE
./install/scripts/docker_unittest_forseti.sh results in tests passing, but lots of errors being outputted

### ISSUE THREAD

**Issue by EricBeach** [GoogleCloudPlatform/forseti-security#1848]
To reproduce:

```bash
$ ./install/scripts/docker_unittest_forseti.sh
```

EXPECTED
Something similar to this:
```bash
$ ./install/scripts/docker_unittest_forseti.sh
Running unittests... 
----------------------------------------------------------------------
Ran 909 tests in 43.074s
OK (skipped=3)
```

ACTUAL
For example, from https://travis-ci.org/GoogleCloudPlatform/forseti-security/builds/411520053
```bash
$ ./install/scripts/docker_unittest_forseti.sh
Running unittests... 
...................................................................................................................................................................................................................................................................................................................................................................................................................ERROR:root:Progressor Warning: "key: owner, data: {'name': 'organizations/111222333'}"
ERROR:root:Progressor Warning: "key: owner, data: {'name': 'organizations/111222333'}"
.ERROR:root:Progressor Warning: u'1014'
.........sqlite:////tmp/tmpC_hnNJ
.................ERROR:google.cloud.forseti.services.dao:Grant not found: (user/u3,r/res1,admin)
ERROR:google.cloud.forseti.services.dao:Grant not found: (user/u3,r/res1,delete)
................ERROR:google.cloud.forseti.services.dao:Etags distinct, stored=075d4bdfea47783994ce1213828f581c, provided=somehash
/forseti-security/.eggs/SQLAlchemy-1.2.10-py2.7-linux-x86_64.egg/sqlalchemy/orm/strategies.py:781: SAWarning: Multiple rows returned with uselist=False for lazily-loaded attribute 'Binding.resource' 
/forseti-security/.eggs/SQLAlchemy-1.2.10-py2.7-linux-x86_64.egg/sqlalchemy/orm/strategies.py:781: SAWarning: Multiple rows returned with uselist=False for lazily-loaded attribute 'Binding.role' 
..ERROR:google.cloud.forseti.services.scanner.dao:Cannot create hash for a violation: 
...ERROR:google.cloud.forseti.services.scanner.dao:Cannot create hash for a violation with algorithm: sha512
......................ERROR: "/what/ever" is not readable.
.ERROR: "/this/does/not/exist" is not a file.
.ERROR: please specify the Forseti config file.
.ERROR: please specify the Forseti database string.
.ERROR:google.cloud.forseti.services.server:Unable to open Forseti Security config file. Please check your path and filename and try again. Error: [Errno 21] Is a directory: '/forseti-security'
..ERROR:google.cloud.forseti.services.server:Unable to open Forseti Security config file. Please check your path and filename and try again. Error: [Errno 2] No such file or directory: '/forseti-security/this_is_a_bad_path.xyz'
.ERROR: please specify at least one service.
........{}
......................CRITICAL:root:enter decorated((0,))
CRITICAL:root:exit decorated((0,)) -> 1
.............................................sss....ERROR:google.cloud.forseti.scanner.scanner:Error running scanner: IamPolicyScanner
Traceback (most recent call last):
  File "/forseti-security/google/cloud/forseti/scanner/scanner.py", line 112, in run
    scanner.run()
  File "/forseti-security/google/cloud/forseti/scanner/scanners/iam_rules_scanner.py", line 256, in run
    policy_data, _ = self._retrieve()
  File "/forseti-security/google/cloud/forseti/scanner/scanners/iam_rules_scanner.py", line 242, in _retrieve
    sys.exit(1)
SystemExit: 1
..........................................................................................................................................................................................ERROR:google.cloud.forseti.notifier.notifier:No success or partial success scanner index found for inventory index: "iid-1-2-3".
...........................................ERROR:google.cloud.forseti.enforcer.project_enforcer:Project test-project could not list firewall rules after enforcement
..ERROR:google.cloud.forseti.enforcer.project_enforcer:Error listing networks for project test-project: <HttpError 403 "Failed">
.ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Response has error: {'code': 'ERROR'}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:The firewall rule {'direction': 'INGRESS', 'network': u'https://www.googleapis.com/compute/beta/projects/test-project/global/networks/test-network', u'sourceRanges': [u'127.0.0.1/32', u'127.0.0.2/32'], u'name': u'test-network-allow-public-0', 'priority': 1000, u'allowed': [{u'IPProtocol': u'ah'}, {u'IPProtocol': u'esp'}, {u'IPProtocol': u'tcp', u'ports': [u'22']}, {u'IPProtocol': u'udp', u'ports': [u'9999']}], u'description': u'Allow public traffic from specific IP addresses.'} for project test-project received the following error response during the last operation: {"status": "DONE", "name": "test-net-allow-corp-internal-0", "error": {"errors": [{"code": "ERROR"}]}}
...ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Response has error: {'code': 'ERROR'}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:The firewall rule {'direction': 'INGRESS', 'network': u'https://www.googleapis.com/compute/beta/projects/test-project/global/networks/test-network', u'sourceRanges': [u'127.0.0.1/32', u'127.0.0.2/32'], u'name': u'test-network-allow-public-0', 'priority': 1000, u'allowed': [{u'IPProtocol': u'ah'}, {u'IPProtocol': u'esp'}, {u'IPProtocol': u'tcp', u'ports': [u'22']}, {u'IPProtocol': u'udp', u'ports': [u'9999']}], u'description': u'Allow public traffic from specific IP addresses.'} for project test-project received the following error response during the last operation: {"status": "DONE", "name": "test-net-allow-all-tcp", "error": {"errors": [{"code": "ERROR"}]}}
................ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Response has error: {'code': 'NOT_FOUND'}
....ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Operation operation-1400179586831 did not complete before timeout of 1.000000, marking operation as failed.
..........ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Error changing firewall rule test-network-allow-internal-0 for project test-project: <HttpError 409 "Duplicate Rule">
...ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Response has error: {'code': 'NOT_FOUND'}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:The firewall rule {'direction': 'INGRESS', 'network': u'https://www.googleapis.com/compute/beta/projects/test-project/global/networks/test-network', 'description': u'Allow internal traffic from a range of IP addresses.', 'sourceRanges': [u'10.0.0.0/8'], 'priority': 1000, 'allowed': [{'IPProtocol': u'icmp'}, {'IPProtocol': u'tcp', 'ports': [u'1-65535']}, {'IPProtocol': u'udp', 'ports': [u'1-65535']}], 'name': u'test-network-allow-internal-0'} for project test-project received the following error response during the last operation: {"status": "DONE", "name": "test", "error": {"errors": [{"code": "NOT_FOUND"}]}}
..ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Response has error: {'code': 'NOT_FOUND'}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:The firewall rule {'direction': 'INGRESS', 'network': u'https://www.googleapis.com/compute/beta/projects/test-project/global/networks/test-network', 'sourceRanges': [u'10.0.0.0/8'], 'name': u'test-network-allow-internal-0', 'priority': 1000, 'allowed': [{'IPProtocol': u'icmp'}, {'IPProtocol': u'tcp', 'ports': [u'1-65535']}, {'IPProtocol': u'udp', 'ports': [u'1-65535']}], 'description': u'Allow internal traffic from a range of IP addresses.'} for project test-project received the following error response during the last operation: {"status": "DONE", "name": "test", "error": {"errors": [{"code": "NOT_FOUND"}]}}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Response has error: {'code': 'NOT_FOUND'}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:The firewall rule {'direction': 'INGRESS', 'network': u'https://www.googleapis.com/compute/beta/projects/test-project/global/networks/test-network', 'sourceRanges': [u'10.0.0.0/8'], 'name': u'test-network-allow-internal-0', 'priority': 1000, 'allowed': [{'IPProtocol': u'icmp'}, {'IPProtocol': u'tcp', 'ports': [u'1-65535']}, {'IPProtocol': u'udp', 'ports': [u'1-65535']}], 'description': u'Allow internal traffic from a range of IP addresses.'} for project test-project received the following error response during the last operation: {"status": "DONE", "name": "test", "error": {"errors": [{"code": "NOT_FOUND"}]}}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:Response has error: {'code': 'NOT_FOUND'}
ERROR:google.cloud.forseti.enforcer.gce_firewall_enforcer:The firewall rule {'direction': 'INGRESS', 'network': u'https://www.googleapis.com/compute/beta/projects/test-project/global/networks/test-network', 'sourceRanges': [u'10.0.0.0/8'], 'name': u'test-network-allow-internal-0', 'priority': 1000, 'allowed': [{'IPProtocol': u'icmp'}, {'IPProtocol': u'tcp', 'ports': [u'1-65535']}, {'IPProtocol': u'udp', 'ports': [u'1-65535']}], 'description': u'Allow internal traffic from a range of IP addresses.'} for project test-project received the following error response during the last operation: {"status": "DONE", "name": "test", "error": {"errors": [{"code": "NOT_FOUND"}]}}
.............................................................................
```

**Comment by EricBeach** [comment]
Running folder by folder, I see a different set of errors.

```bash
$ docker -l error exec -it build /bin/bash -c "python -m unittest discover -s tests/actions -p '*_test.py'"
...................
----------------------------------------------------------------------
Ran 19 tests in 0.016s

$ docker -l error exec -it build /bin/bash -c "python -m unittest discover -s tests/common -p '*_test.py'"
...............................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 399 tests in 6.989s

$ docker -l error exec -it build /bin/bash -c "python -m unittest discover -s tests/enforcer -p '*_test.py'"
......................................................................................................
----------------------------------------------------------------------
Ran 102 tests in 2.215s

$ docker -l error exec -it build /bin/bash -c "python -m unittest discover -s tests/gcp -p '*_test.py'"
......................................
----------------------------------------------------------------------
Ran 38 tests in 0.652s

$ docker -l error exec -it build /bin/bash -c "python -m unittest discover -s tests/notifier -p '*_test.py'"
.................................ERROR:google.cloud.forseti.notifier.notifier:No success or partial success scanner index found for inventory index: "iid-1-2-3".
..
----------------------------------------------------------------------
Ran 35 tests in 0.632s

$ docker -l error exec -it build /bin/bash -c "python -m unittest discover -s tests/scanner -p '*_test.py'"
....ERROR:google.cloud.forseti.scanner.scanner:Error running scanner: IamPolicyScanner
Traceback (most recent call last):
  File "/forseti-security/google/cloud/forseti/scanner/scanner.py", line 112, in run
    scanner.run()
  File "/forseti-security/google/cloud/forseti/scanner/scanners/iam_rules_scanner.py", line 256, in run
    policy_data, _ = self._retrieve()
  File "/forseti-security/google/cloud/forseti/scanner/scanners/iam_rules_scanner.py", line 242, in _retrieve
    sys.exit(1)
SystemExit: 1
.sss....................................................................................................................................................................................
----------------------------------------------------------------------
Ran 188 tests in 1.998s

$ docker -l error exec -it build /bin/bash -c "python -m unittest discover -s tests/services -p '*_test.py'"                                        ..................CRITICAL:root:enter decorated((0,))                                                                                                                                                  CRITICAL:root:exit decorated((0,)) -> 1                                                                                                                                                                .....ERROR:google.cloud.forseti.services.scanner.dao:Cannot create hash for a violation:                                                                                                               
                                                                                                                                                                                                       ...ERROR:google.cloud.forseti.services.scanner.dao:Cannot create hash for a violation with algorithm: sha512                                                                                                                                                                                                                                                                                                  .................................ERROR:google.cloud.forseti.services.dao:Grant not found: (user/u3,r/res1,admin)                                                                                       ERROR:google.cloud.forseti.services.dao:Grant not found: (user/u3,r/res1,delete)                                                                                                                       ................ERROR:google.cloud.forseti.services.dao:Etags distinct, stored=3956305d8f2b9efcf3cc120975831dfc, provided=somehash                                                                     /forseti-security/.eggs/SQLAlchemy-1.2.10-py2.7-linux-x86_64.egg/sqlalchemy/orm/strategies.py:781: SAWarning: Multiple rows returned with uselist=False for lazily-loaded attribute 'Binding.resource' /forseti-security/.eggs/SQLAlchemy-1.2.10-py2.7-linux-x86_64.egg/sqlalchemy/orm/strategies.py:781: SAWarning: Multiple rows returned with uselist=False for lazily-loaded attribute 'Binding.role'     .....{}                                                                                                                                                                                                .......sqlite:////tmp/tmpsLRiif                                                                                                                                                                        ......ERROR: "/what/ever" is not readable.                                                                                                                                                                                                                                                                                                                                                                    .ERROR: "/this/does/not/exist" is not a file.                                                                                                                                                                                                                                                                                                                                                                 .ERROR: please specify the Forseti config file. 

.ERROR: please specify the Forseti database string.                                                                                                                                                                                                                                                                                                                                                           .ERROR:google.cloud.forseti.services.server:Unable to open Forseti Security config file. Please check your path and filename and try again. Error: [Errno 21] Is a directory: '/forseti-security'      ..ERROR:google.cloud.forseti.services.server:Unable to open Forseti Security config file. Please check your path and filename and try again. Error: [Errno 2] No such file or directory: '/forseti-security/this_is_a_bad_path.xyz'                                                                                                                                                                           .ERROR: please specify at least one service.                                                                                                                                                                                                                                                                                                                                                                  ........ERROR:root:Progressor Warning: "key: owner, data: {'name': 'organizations/111222333'}"                                                                                                         ERROR:root:Progressor Warning: "key: owner, data: {'name': 'organizations/111222333'}"                                                                                                                 .ERROR:root:Progressor Warning: u'1014'                                                                                                                                                                ....                                                                                                                                                                                                   ----------------------------------------------------------------------                                                                                                                                 Ran 113 tests in 32.802s  

```

**Comment by EricBeach** [comment]
Specific test that generates a lot of errors.

```bash
$ docker -l error exec -it build /bin/bash -c "python -m unittest --verbose tests.scanner.scanner_test.ScannerRunnerTest.test_scanner_index_id_can_be_correctly_initialized"
test_scanner_index_id_can_be_correctly_initialized (tests.scanner.scanner_test.ScannerRunnerTest)
Test that the 'scanner_index_id' *is* initialized. ... ERROR:google.cloud.forseti.scanner.scanner:Error running scanner: IamPolicyScanner
Traceback (most recent call last):
  File "/forseti-security/google/cloud/forseti/scanner/scanner.py", line 112, in run
    scanner.run()
  File "/forseti-security/google/cloud/forseti/scanner/scanners/iam_rules_scanner.py", line 256, in run
    policy_data, _ = self._retrieve()
  File "/forseti-security/google/cloud/forseti/scanner/scanners/iam_rules_scanner.py", line 242, in _retrieve
    sys.exit(1)
SystemExit: 1
ok

----------------------------------------------------------------------
Ran 1 test in 0.434s

OK
```

**Comment by EricBeach** [comment]
So after a good bit of digging into this, many (perhaps most) of the ERROR logs in Travis appear to be valid (i.e., intended). The root issue is that https://github.com/GoogleCloudPlatform/forseti-security/blob/dev/tests/unittest_utils.py#L55 sets the log level to ERROR, so for tests that will rightly generate ERROR such as inputting malformed data, we will see errors in the logs.

So, it seems we have a few options:
(1) tolerate the errors in the logs since they are intended
(2) change error logging level (trying even to change it on a per-test basis when it is intended)

@blueandgold - any input on how this should be treated?

**Comment by blueandgold** [comment]
Thanks for tracking this down!  I do not know of any actual use for the logging on the error level, so it would be nice to change the levels to quiet them, and it would be easy to enable it on specific tests if necessary.  How do you think? @EricBeach

**Comment by EricBeach** [comment]
Re-opening as there is one more PR (#1929) waiting for review before this is fully closed.

**Comment by EricBeach** [comment]
With the submission of #1929, I believe this is now complete!
