### ISSUE TITLE
IAP scanner will fail if the network property of instanceGroup is empty

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#1918]
2018-08-20 20:05:53,579 INFO [forseti-security] google.cloud.forseti.scanner.scanners.iap_scanner(_find_violations): Finding IAP violations with <google.cloud.forseti.scanner.audit.iap
_rules_engine.IapRulesEngine object at 0x7f125c1a8550>...
2018-08-20 20:05:54,110 ERROR [forseti-security] google.cloud.forseti.scanner.scanners.iap_scanner(instance_group_network_port): NetworkPort can not be constructed. Unable to find the 
appropriate port from backend service or instance group.
2018-08-20 20:05:54,463 ERROR [forseti-security] google.cloud.forseti.scanner.scanners.iap_scanner(instance_group_network_port): NetworkPort can not be constructed. Unable to find the 
appropriate port from backend service or instance group.
2018-08-20 20:05:54,463 ERROR [forseti-security] google.cloud.forseti.scanner.scanners.iap_scanner(instance_group_network_port): NetworkPort can not be constructed. Unable to find the 
appropriate port from backend service or instance group.
2018-08-20 20:05:54,463 ERROR [forseti-security] google.cloud.forseti.scanner.scanners.iap_scanner(instance_group_network_port): NetworkPort can not be constructed. Unable to find the 
appropriate port from backend service or instance group.
2018-08-20 20:05:54,689 ERROR [forseti-security] google.cloud.forseti.scanner.scanner(run): Error running scanner: IapScanner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 112, in run
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 634, in run
    all_violations, _ = self._find_violations(iap_data)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 619, in _find_violations
    for (iap_resources, project_resource_counts) in iap_data:
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 602, in _retrieve
    run_data.make_iap_resource(backend, parent.full_name))
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 321, in make_iap_resource
    if self.is_alternate_service(backend_service, backend_service2):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 361, in is_alternate_service
    backend_service2, instance_group2)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 140, in instance_group_network_port
    project_id=instance_group.project_id),
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/common/gcp_type/network.py", line 64, in from_url
    if '://' not in url:
TypeError: argument of type 'NoneType' is not iterable

**Comment by joecheuk** [comment]
Updated stacktrace when running iap scanner

`google.cloud.forseti.scanner.scanner(run): Error running scanner: IapScanner Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 113, in run scanner.run() File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 635, in run all_violations, _ = self._find_violations(iap_data) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 620, in _find_violations for (iap_resources, project_resource_counts) in iap_data: File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 603, in _retrieve run_data.make_iap_resource(backend, parent.full_name)) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 291, in make_iap_resource backend.get('group')) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 152, in find_instance_group_by_url target_key = instance_group_type.Key.from_url(instance_group_url) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/common/gcp_type/instance_group.py", line 195, in from_url url) File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.8.0-py2.7.egg/google/cloud/forseti/common/gcp_type/key.py", line 104, in _from_url path_components = urlparse.urlparse(url)[2].split('/')[3:] File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse tuple = urlsplit(url, scheme, allow_fragments) File "/usr/lib/python2.7/urlparse.py", line 182, in urlsplit i = url.find(':') AttributeError: 'NoneType' object has no attribute 'find'`

**Comment by jf-marquis-Adeo** [comment]
seems to be present in  2.13.0
2019-04-03 10:46:10,952 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Looking for IAP violations: IapResource(project_full_name=u'organization/899064685583/folder/457815117631/folder/150093548869/folder/736583365201/folder/371694806870/project/manawa-euw4-dtp/', backend_service=backendservice<id=333020148442725244,parent=None>, alternate_services=set([]), direct_access_sources=set([u'0.0.0.0/0']), iap_enabled=False)
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Ancestors of resource: [project<id=manawa-euw4-dtp,parent=None>, folder<id=371694806870,parent=None>, folder<id=736583365201,parent=None>, folder<id=150093548869,parent=None>, folder<id=457815117631,parent=None>, organization<id=899064685583,parent=None>]
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for project<id=manawa-euw4-dtp,parent=None>: []
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=371694806870,parent=None>: []
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=736583365201,parent=None>: []
2019-04-03 10:46:10,953 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=150093548869,parent=None>: []
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for folder<id=457815117631,parent=None>: []
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Resource rules for organization<id=899064685583,parent=None>: [IapResourceRules<resource=organization<id=*,parent=None>, rules=set([IapRule<rule_name=Forbid any IAP bypasses (when IAP is enabled), rule_index=0, allowed_alternate_services=[], allowed_direct_access_sources=[], allowed_iap_enabled=^.*$>]), applies_to=self_and_children, inherit_from_parents=True>]
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Does IapResourceRules<resource=organization<id=*,parent=None>, rules=set([IapRule<rule_name=Forbid any IAP bypasses (when IAP is enabled), rule_index=0, allowed_alternate_services=[], allowed_direct_access_sources=[], allowed_iap_enabled=^.*$>]), applies_to=self_and_children, inherit_from_parents=True> apply to resource? True
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Has enabled violation? '^.*$' / False
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Enabled violation: False
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Has alternate service violation? False / [] / set([])
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Alternate services violations: []
2019-04-03 10:46:10,954 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Has sources violation? False / [] / set([u'0.0.0.0/0'])
2019-04-03 10:46:10,955 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_mismatches): Sources violations: []
2019-04-03 10:46:10,955 DEBUG [forseti-security][2.13.0] google.cloud.forseti.scanner.audit.iap_rules_engine(find_violations): Returning violations: []
2019-04-03 10:46:11,065 ERROR [forseti-security][2.13.0] google.cloud.forseti.scanner.scanner(run): Error running scanner: IapScanner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 117, in run
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 642, in run
    all_violations, _ = self._find_violations(iap_data)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 627, in _find_violations
    for (iap_resources, project_resource_counts) in iap_data:
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 610, in _retrieve
    run_data.make_iap_resource(backend, parent.full_name))
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 300, in make_iap_resource
    backend_service, instance_group)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py", line 141, in instance_group_network_port
    project_id=instance_group.project_id),
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.13.0-py2.7.egg/google/cloud/forseti/common/gcp_type/network.py", line 64, in from_url
    if '://' not in url:
TypeError: argument of type 'NoneType' is not iterable
