### ISSUE TITLE
Group scanner failed when loading rule file.

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#2024]
```
2018-09-20 14:55:25,119 ERROR google.cloud.forseti.scanner.scanner(run): Error running scanner: GroupsScanner
Traceback (most recent call last):
  File "forseti-security/google/cloud/forseti/scanner/scanner.py", line 111, in run
    scanner.run()
  File "forseti-security/google/cloud/forseti/scanner/scanners/groups_scanner.py", line 265, in run
    group_rules = file_loader.read_and_parse_file(f)
  File "forseti-security/google/cloud/forseti/common/util/file_loader.py", line 38, in read_and_parse_file
    file_path = file_path.strip()
AttributeError: 'file' object has no attribute 'strip'
```

**Comment by blueandgold** [comment]
@red2k18 Please update 2.4.0 tag to include the fix for this....thanks!
