### ISSUE TITLE
Another DB Session out of sync: "Commands out of sync; you can't run this command now"

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#2027]
We have fixed a similar issue before in #1718. We can not have multiple simultaneous queries in in the same session.

2018-09-12 13:21:29,472 ERROR [forseti-security] google.cloud.forseti.scanner.scanner(run): Error running scanner: BigqueryScanner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.2.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 111, in run
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.2.0-py2.7.egg/google/cloud/forseti/scanner/scanners/bigquery_scanner.py", line 179, in run
    bigquery_acl_data = self._retrieve()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.2.0-py2.7.egg/google/cloud/forseti/scanner/scanners/bigquery_scanner.py", line 144, in _retrieve
    if dataset.parent.type != 'project':
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/attributes.py", line 242, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/attributes.py", line 599, in get
    value = self.callable_(state, passive)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/strategies.py", line 631, in _load_for_state
    session, state, primary_key_identity, passive)
  File "<string>", line 1, in <lambda>
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/strategies.py", line 724, in _emit_lazyload
    primary_key_identity)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/ext/baked.py", line 508, in _load_on_pk_identity
    result = list(bq.for_session(self.session).params(**params))
  File "build/bdist.linux-x86_64/egg/sqlalchemy/ext/baked.py", line 353, in __iter__
    return q._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'SELECT `97bf29922374d342df55b22740dee002_resources`.full_name AS `97bf29922374d342df55b22740dee002_resources_full_name`, `97bf29922374d342df55b22740dee002_resources`.type_name AS `97bf29922374d342df55b22740dee002_resources_type_name`, `97bf29922374d342df55b22740dee002_resources`.parent_type_name AS `97bf29922374d342df55b22740dee002_resources_parent_type_name`, `97bf29922374d342df55b22740dee002_resources`.name AS `97bf29922374d342df55b22740dee002_resources_name`, `97bf29922374d342df55b22740dee002_resources`.type AS `97bf29922374d342df55b22740dee002_resources_type`, `97bf29922374d342df55b22740dee002_resources`.policy_update_counter AS `97bf29922374d342df55b22740dee002_resources_policy_update_counter`, `97bf29922374d342df55b22740dee002_resources`.display_name AS `97bf29922374d342df55b22740dee002_resources_display_name`, `97bf29922374d342df55b22740dee002_resources`.email AS `97bf29922374d342df55b22740dee002_resources_email`, `97bf29922374d342df55b22740dee002_resources`.data AS `97bf29922374d342df55b22740dee002_resources_data` \nFROM `97bf29922374d342df55b22740dee002_resources` \nWHERE `97bf29922374d342df55b22740dee002_resources`.type_name = %s'] [parameters: ('project/xyz_project',)] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by blueandgold** [comment]
Another user has reported on this.
