### ISSUE TITLE
Dev branch broken

### ISSUE THREAD

**Issue by ocervell** [GoogleCloudPlatform/forseti-security#2031]
Latest dev branch is breaking with the following exception:

```
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]: Traceback (most recent call last): 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:   File "/usr/local/bin/forseti_server", line 11, in <module> 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:     load_entry_point('forseti-security==2.0.0', 'console_scripts', 'forseti_server')() 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:   File "/home/ubuntu/forseti-security/google/cloud/forseti/stubs.py", line 27, in RunForsetiServer 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:     import google.cloud.forseti.services.server as forseti_server 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:   File "/home/ubuntu/forseti-security/google/cloud/forseti/services/server.py", line 29, in <module> 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:     from google.cloud.forseti.services.base.config import ServiceConfig 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:   File "/home/ubuntu/forseti-security/google/cloud/forseti/services/base/config.py", line 31, in <module> 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:     from google.cloud.forseti.services.inventory.storage import Storage 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:   File "/home/ubuntu/forseti-security/google/cloud/forseti/services/inventory/storage.py", line 38, in <module> 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]:     from google.cloud.asset_v1beta1.proto import assets_pb2 
A  Sep 21 21:26:25 forseti-server-vm-ad9ac13 forseti_server[27076]: ImportError: No module named asset_v1beta1.proto
```

**Comment by jjawad-google** [comment]
Please try running pip install -r requirements.txt. This should fix your dev environment.
