### ISSUE TITLE
[v2.9.0] Location Scanner error

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#2368]
```
[forseti-security][2.9.0] google.cloud.forseti.scanner.scanner(run): Error running scanner: LocationScanner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 117, in run
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/scanner/scanners/location_scanner.py", line 57, in run
    resources = self._retrieve()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/scanner/scanners/location_scanner.py", line 89, in _retrieve
    resource_type, proj, resource.data))
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/common/gcp_type/resource_util.py", line 124, in create_resource_from_json
    return resource_type.get('class').from_json(parent, json_string)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.9.0-py2.7.egg/google/cloud/forseti/common/gcp_type/dataset.py", line 89, in from_json
    locations=[dataset_dict['location']],
KeyError: 'location'
```

**Comment by joecheuk** [comment]
The bigquery dataset data provided by CAI doesn't include field "location", workaround is to disable using bigquery dataset data from CAI for now.
