### ISSUE TITLE
Foreign key constraint fails in the resources table

### ISSUE THREAD

**Issue by joecheuk** [GoogleCloudPlatform/forseti-security#2504]
Cannot add or update a child row: a foreign key constraint fails (`forseti_security`.`80a00fd7b40e6752adc80a27839b0bd3_resources`, CONSTRAINT `80a00fd7b40e6752adc80a27839b0bd3_resources_ibfk_1` FOREIGN KEY (`parent_type_name`) REFERENCES `80a00fd7b40e6752adc)') [SQL: u'INSERT INTO `80a00fd7b40e6752adc80a27839b0bd3_resources` (full_name, type_name, parent_type_name, name, type, policy_update_counter, display_name, email, data) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (('organization/660570133860/iam_policy/organization:660570133860/', 'iam_policy/organization:660570133860', 'organization/660570133860', u'660570133860', 'iam_policy', 0, '', '', u'{"auditConfigs": [{"auditLogConfigs": [{"logType": "ADMIN_READ"}, {"logType": "DATA_WRITE"}], "service": "allServices"}], "bindings": [{"members": [ ... (124316 characters truncated) ... elix@henrychang.mygbiz.com", "user:jiyun@henrychang.mygbiz.com", "user:joe@henrychang.mygbiz.com"], "role": "roles/viewer"} Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.10.0-py2.7.egg/google/cloud/forseti/services/model/importer/importer.py", line 298, in run self._store_iam_policy File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.10.0-py2.7.egg/google/cloud/forseti/services/model/importer/importer.py", line 359, in model_action_wrapper session.flush() File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2313, in flush self._flush(objects) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2440, in _flush transaction.rollback(_capture_exception=True) File "build/bdist.linux-x86_64/egg/sqlalchemy/util/langhelpers.py", line 66, in __exit__ compat.reraise(exc_type, exc_value, exc_tb) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 2404, in _flush flush_context.execute() File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 395, in execute rec.execute(self) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/unitofwork.py", line 560, in execute uow File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 181, in save_obj mapper, table, insert) File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/persistence.py", line 836, in _emit_insert_statements execute(statement, multiparams) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 948, in execute return meth(self, multiparams, params) File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection return connection._execute_clauseelement(self, multiparams, params) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement compiled_sql, distilled_params File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1200, in _execute_context context) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception exc_info File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 265, in raise_from_cause reraise(type(exception), exception, tb=exc_tb, cause=cause) File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1170, in _execute_context context) File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/mysql/mysqldb.py", line 105, in do_executemany rowcount = cursor.executemany(statement, parameters) File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 262, in executemany r = self._query('\n'.join([query[:p], ',\n'.join(q), query[e:]])) File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 354, in _query rowcount = self._do_query(q) File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 318, in _do_query db.query(q) IntegrityError: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`forseti_security`.`80a00fd7b40e6752adc80a27839b0bd3_resources`, CONSTRAINT `80a00fd7b40e6752adc80a27839b0bd3_resources_ibfk_1` FOREIGN KEY (`parent_type_name`) REFERENCES `80a00fd7b40e6752adc)') [SQL: u'INSERT INTO `80a00fd7b40e6752adc80a27839b0bd3_resources` (full_name, type_name, parent_type_name, name, type, policy_update_counter, display_name, email, data) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (('organization/660570133860/iam_policy/organization:660570133860/', 'iam_policy/organization:660570133860', 'organization/660570133860', u'660570133860', 'iam_policy', 0, '', '', u'{"auditConfigs": [{"auditLogConfigs": [{"logType": "ADMIN_READ"}, {"logType": "DATA_WRITE"}], "service": "allServices"}], "bindings": [{"members": [ ... (124316 characters truncated) ... elix@henrychang.mygbiz.com", "user:jiyun@henrychang.mygbiz.com", "user:joe@henrychang.mygbiz.com"], "role": "roles/viewer"}], "etag": "BwV/JeSHyQY="}'), ('organization/660570133860/billing_account/00469A-6990E4-53722E/iam_policy/billing_account:00469A-6990E4-53722E/', 'iam_policy/billing_account:00469A-6990E4-53722E', 'billing_account/00469A-6990E4-53722E', u'00469A-6990E4-53722E', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["user:henry@henrychang.mygbiz.com"], "role": "roles/billing.admin"}], "etag": "BwU9mSIYT1g="}'), ('organization/660570133860/billing_account/018577-7DDAB5-AD9AA5/iam_policy/billing_account:018577-7DDAB5-AD9AA5/', 'iam_policy/billing_account:018577-7DDAB5-AD9AA5', 'billing_account/018577-7DDAB5-AD9AA5', u'018577-7DDAB5-AD9AA5', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["user:marten@henrychang.mygbiz.com"], "role": "roles/billing.admin"}], "etag": "BwV7TEkSEBk="}'), ('organization/660570133860/folder/1031398079441/iam_policy/folder:1031398079441/', 'iam_policy/folder:1031398079441', 'folder/1031398079441', u'1031398079441', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["serviceAccount:forseti-server-gcp-3057f11@henry-2-4-0.iam.gserviceaccount.com", "serviceAccount:forseti-server-gcp-79c43 ... (2472 characters truncated) ... : ["serviceAccount:forseti-server-gcp-79c4374@henryuser-noorgaccess-0706.iam.gserviceaccount.com"], "role": "roles/viewer"}], "etag": "BwVwmkNFKiw="}'), ('organization/660570133860/folder/138672061205/iam_policy/folder:138672061205/', 'iam_policy/folder:138672061205', 'folder/138672061205', u'138672061205', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["serviceAccount:890845777166-compute@developer.gserviceaccount.com", "serviceAccount:henryfoldersubset@inventoryscanner-h ... (1856 characters truncated) ... Account:henryfoldersubset@inventoryscanner-henry.iam.gserviceaccount.com"], "role": "roles/serviceusage.serviceUsageAdmin"}], "etag": "BwV0eLLtCDU="}'), ('organization/660570133860/folder/183126224153/iam_policy/folder:183126224153/', 'iam_policy/folder:183126224153', 'folder/183126224153', u'183126224153', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["serviceAccount:inventoryloader@inventoryscanner-henry.iam.gserviceaccount.com", "user:henry@henrychang.mygbiz.com"], "ro ... (15 characters truncated) ... ourcemanager.folderAdmin"}, {"members": ["user:henry@henrychang.mygbiz.com"], "role": "roles/resourcemanager.folderEditor"}], "etag": "BwVPk6g/3yI="}'), ('organization/660570133860/folder/606257831695/iam_policy/folder:606257831695/', 'iam_policy/folder:606257831695', 'folder/606257831695', u'606257831695', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["user:shinhannah@henrychang.mygbiz.com"], "role": "roles/resourcemanager.folderAdmin"}, {"members": ["user:shinhannah@henrychang.mygbiz.com"], "role": "roles/resourcemanager.folderEditor"}], "etag": "BwV7C7qeYO4="}'), ('organization/660570133860/folder/296295060980/iam_policy/folder:296295060980/', 'iam_policy/folder:296295060980', 'folder/296295060980', u'296295060980', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["serviceAccount:forseti-service-0707@jiyun-test.iam.gserviceaccount.com", "serviceAccount:jiyun-crawling-scraping@jiyun-t ... (85 characters truncated) ... ourcemanager.folderAdmin"}, {"members": ["user:jiyun@henrychang.mygbiz.com"], "role": "roles/resourcemanager.folderEditor"}], "etag": "BwVfUILe/+Y="}') ... displaying 10 of 586 total bound parameter sets ... ('organization/660570133860/folder/138672061205/folder/37188445764/project/forseti-test-110/bucket/staging.forseti-test-110.appspot.com/iam_policy/bucket:staging.forseti-test-110.appspot.com/', 'iam_policy/bucket:staging.forseti-test-110.appspot.com', 'bucket/staging.forseti-test-110.appspot.com', u'staging.forseti-test-110.appspot.com', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["projectEditor:forseti-test-110", "projectOwner:forseti-test-110"], "role": "roles/storage.legacyBucketOwner"}, {"members": ["projectViewer:forseti-test-110"], "role": "roles/storage.legacyBucketReader"}], "etag": "ACAB"}'), ('organization/660570133860/folder/138672061205/folder/37188445764/project/jiyun-test/bucket/scanner-jiyun-0731/iam_policy/bucket:scanner-jiyun-0731/', 'iam_policy/bucket:scanner-jiyun-0731', 'bucket/scanner-jiyun-0731', u'scanner-jiyun-0731', 'iam_policy', 0, '', '', u'{"bindings": [{"members": ["projectEditor:jiyun-test", "projectOwner:jiyun-test"], "role": "roles/storage.legacyBucketOwner"}, {"members": ["projectViewer:jiyun-test"], "role": "roles/storage.legacyBucketReader"}], "etag": "ACAB"}'))] (Background on this error at: http://sqlalche.me/e/gkpj)

**Comment by joecheuk** [comment]
Related #2467

**Comment by joecheuk** [comment]
Can't reproduce after running the instance for few days with cronjob set to run per minute. Will reopen this in the future if it happens again.
