### ISSUE TITLE
CAI parser floods error messages when MySQL connection drops

### ISSUE THREAD

**Issue by rgmenon** [GoogleCloudPlatform/forseti-security#2574]
- [x] Which version of Forseti Security you're using (look in `google/cloud/security/__init__.py` in your installation).
2.11.0

 - [x] Which module(s) (inventory, scanner, enforcer, explain) you're having trouble with.
Inventory - CAI parsing

 - [x] Include errors, log output, and host operating system, including installed packages.
 - [x] Note how you deployed (via Deployment Manager, local system, etc.).
Deployment Manager

When large deployments are being inventoried, MySQL connection drops (sporadically!). But the parsing of the CAI data does not handle this gracefully resulting in flood of errors (which go into the in the inventory_index table's error message column. Below is an example sequence where I was able to catch both the MySQL connection drop and the resulting flood of exceptions.AttributeError attributes (only 1 exception is displayed :-) below:

[forseti-security][2.11.0] google.cloud.forseti.services.inventory.base.resources(accept): (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') (Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/base/resources.py", line 300, in accept
    for resource in yielder.iter():
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/base/resources.py", line 1531, in iter
    for data in iter_method(*args, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/base/cai_gcp_client.py", line 328, in iter_compute_disks
    for disk in resources:
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.py", line 830, in iter_cai_assets
    for row in base_query.yield_per(PER_YIELD):
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/loading.py", line 77, in instances
    fetch = cursor.fetchmany(query._yield_per)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py", line 1247, in fetchmany
    e, None, None, self.cursor, self.context
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py", line 1241, in fetchmany
    l = self.process_rows(self._fetchmany_impl(size))
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py", line 1401, in _fetchmany_impl
    row = self._fetchone_impl()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py", line 1391, in _fetchone_impl
    self.__buffer_rows()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/result.py", line 1378, in __buffer_rows
    self.__rowbuffer = collections.deque(self.cursor.fetchmany(size))
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 441, in fetchmany
    r = self._fetch_row(size or self.arraysize)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 327, in _fetch_row
    return self._result.fetch_row(size, self._fetch_type)
OperationalError: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') (Background on this error at: http://sqlalche.me/e/e3q8) 
  undefined

[forseti-security][2.11.0] google.cloud.forseti.services.inventory.base.resources(accept): (exceptions.AttributeError) 'NoneType' object has no attribute 'cursor' [SQL: u'SELECT cai_temporary_store.name AS cai_temporary_store_name, cai_temporary_store.parent_name AS cai_temporary_store_parent_name, cai_temporary_store.content_type AS cai_temporary_store_content_type, cai_temporary_store.asset_type AS cai_temporary_store_asset_type, cai_temporary_store.asset_data AS cai_temporary_store_asset_data \nFROM cai_temporary_store \nWHERE cai_temporary_store.content_type = %s AND cai_temporary_store.asset_type = %s AND cai_temporary_store.parent_name = %s ORDER BY cai_temporary_store.name ASC'] [parameters: [{}]]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/base/resources.py", line 300, in accept
    for resource in yielder.iter():
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/base/resources.py", line 1531, in iter
    for data in iter_method(*args, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/base/cai_gcp_client.py", line 351, in iter_compute_firewalls
    for rule in resources:
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.0-py2.7.egg/google/cloud/forseti/services/inventory/storage.py", line 830, in iter_cai_assets
    for row in base_query.yield_per(PER_YIELD):
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 3112, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 3137, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 974, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1093, in _execute_clauseelement
    distilled_params,
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1168, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1452, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1165, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 672, in _init_compiled
    self.cursor = self.create_cursor()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 1015, in create_cursor
    return self.create_server_side_cursor()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/dialects/mysql/base.py", line 1147, in create_server_side_cursor
    return self._dbapi_connection.cursor(self.dialect._sscursor)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 1016, in cursor
    return self.connection.cursor(*args, **kwargs)
StatementError: (exceptions.AttributeError) 'NoneType' object has no attribute 'cursor' [SQL: u'SELECT cai_temporary_store.name AS cai_temporary_store_name, cai_temporary_store.parent_name AS cai_temporary_store_parent_name, cai_temporary_store.content_type AS cai_temporary_store_content_type, cai_temporary_store.asset_type AS cai_temporary_store_asset_type, cai_temporary_store.asset_data AS cai_temporary_store_asset_data \nFROM cai_temporary_store \nWHERE cai_temporary_store.content_type = %s AND cai_temporary_store.asset_type = %s AND cai_temporary_store.parent_name = %s ORDER BY cai_temporary_store.name ASC'] [parameters: [{}]] 
  undefined

**Comment by jf-marquis-Adeo** [comment]
same problem on my side with 13700 Datasets in Bigquery

**Comment by hshin-g** [comment]
@rgmenon @jf-marquis-Adeo What CloudSQL instance size are you using?

**Comment by rgmenon** [comment]
> What CloudSQL instance size are you using?
db-n1-standard-1 (I used DM stock install and did not change _any_ defaults)

> It could be worth sizing up and seeing if that solves the issue
Not specific to this issue but I have tried tuning CloudSQL but unfortunately, CloudSQL connections do drop and there are some _long_ standing issues on this front. See for example https://issuetracker.google.com/issues/35904221 (see the blocking issues as well)

IMO, the client must be prepared for this to happen and handle it gracefully.

**Comment by joecheuk** [comment]
Haven't backport the changes yet, will keep this open

**Comment by red2k18** [comment]
Testing is in-progress.

**Comment by dekuhn** [comment]
Any update on this P0 issue? What is needed here to move this to resolution.

**Comment by osandoval011** [comment]
@dekuhn I believe this was fixed by: https://github.com/GoogleCloudPlatform/forseti-security/commit/53ef39e04854b77814dd11d2c83595587f99bc7e

**Comment by osandoval011** [comment]
Fixed by #2672
