### ISSUE TITLE
Error running resource scanner with folders

### ISSUE THREAD

**Issue by dufton** [GoogleCloudPlatform/forseti-security#2613]
Resource scanner will fail if the scanned hierarchy contains a folder.

Relevant stack trace:
```
Error running scanner: ResourceScanner
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.1-py2.7.egg/google/cloud/forseti/scanner/scanner.py", line 117, in run
    scanner.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.1-py2.7.egg/google/cloud/forseti/scanner/scanners/resource_scanner.py", line 56, in run
    resources = self._retrieve()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.1-py2.7.egg/google/cloud/forseti/scanner/scanners/resource_scanner.py", line 79, in _retrieve
    resource_util.create_resource_from_db_row(resource)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.1-py2.7.egg/google/cloud/forseti/common/gcp_type/resource_util.py", line 127, in create_resource_from_db_row
    create_resource_from_db_row(row.parent) if row.parent else None)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.1-py2.7.egg/google/cloud/forseti/common/gcp_type/resource_util.py", line 129, in create_resource_from_db_row
    return create_resource_from_json(row.type, parent, row.data)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.11.1-py2.7.egg/google/cloud/forseti/common/gcp_type/resource_util.py", line 150, in create_resource_from_json
    return resource_type.get('class').from_json(parent, json_string)
AttributeError: type object 'Folder' has no attribute 'from_json'"
```

**Comment by joecheuk** [comment]
Resolved #2615
