### ISSUE TITLE
Slack notification cause traceback errors

### ISSUE THREAD

**Issue by brandon-height** [GoogleCloudPlatform/forseti-security#848]
-  Forseti Security version: "1.1.7"
 -  Notifier is the problem module
 - Setup Wizard (Forseti is in an isolated project)

In notifier section of forseti_conf.yaml:
```
            - name: slack_webhook_pipeline
              configuration:
                webhook_url: '<excluded>'
```
If the above is included in any resource under the notifier section I receive the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-1.1.7-py2.7.egg/google/cloud/security/notifier/notifier.py", line 225, in <module>
    app.run()
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/app.py", line 238, in run
    return _actual_start()
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/app.py", line 267, in _actual_start
    really_start()
  File "/usr/local/lib/python2.7/dist-packages/google/apputils/app.py", line 220, in really_start
    sys.exit(main(argv))
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-1.1.7-py2.7.egg/google/cloud/security/notifier/notifier.py", line 221, in main
    pipeline.run()
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-1.1.7-py2.7.egg/google/cloud/security/notifier/pipelines/slack_webhook_pipeline.py", line 96, in run
    webhook_payload = self._compose(violation=violation)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-1.1.7-py2.7.egg/google/cloud/security/notifier/pipelines/slack_webhook_pipeline.py", line 70, in _compose
    'details': json.loads(violation.get('violation_data'))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
```
I dropped a print statement into google/cloud/security/notifier/pipelines/slack_webhook_pipeline.py
in the _compose() method to print out the violation_data it attempts to json.loads()
```print(violation.get('violation_data'))```

After installing my change and manually running forseti I can see the offending violation_data:
```{u'access_user_by_email': u'<sanitized>', u'access_special_group': u'', u'access_domain': u'', u'access_group_by_email': u'', u'role': u'OWNER', u'dataset_id': u'_ff7ae1c00d0f36122710990e751983fb5c476b6b'}```

which is what json.loads() is failing on.

**Comment by blueandgold** [comment]
Can you please try this: change the ```json.loads()``` to ```json.dumps()```?  Does that help?

**Comment by brandon-height** [comment]
That fixes it -- @blueandgold

**Comment by blueandgold** [comment]
Super, we will fix this and push it out in the next release.

**Comment by blueandgold** [comment]
The problem is [coming from here](https://github.com/GoogleCloudPlatform/forseti-security/pull/762/files#diff-35e1e2967889bcc1d9049e770706aee7R164), where json.loads() is called upstream, when then causes problem in the slack notification when json.loads() is called again.

**Comment by blueandgold** [comment]
Fixed, and needs to be pushed out to master.
