### ISSUE TITLE
Model Creation Error

### ISSUE THREAD

**Issue by blueandgold** [GoogleCloudPlatform/forseti-security#882]
I am trying to test the scanner integration with the most recent updated code.  But when I try to create the model, I get the following error:

```
forseti inventory create
forseti model create inventory --id 82 henry4ccc
```

```
ERROR:root:Exception calling application: (_mysql_exceptions.DataError) (1406, "Data too long for column 'warnings' at row 1") [SQL: u'UPDATE model SET state=%s, message=%s, warnings=%s WHERE model.name = %s'] [parameters: ('PARTIAL_SUCCESS', 1656, 'Role missing permissions: roles/containeranalysis.notes.attacher\nRole missing permissions: roles/resourcemanager.organizationCreator\nRole reference ... (216651 characters truncated) ... projects/stable-device-182522?fields=name&alt=json returned "Required \'compute.projects.get\' permission for \'projects/stable-device-182522\'">\n\n', 'henry4ccc')]
Traceback (most recent call last):
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/grpc/_server.py", line 390, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/google/home/henryc/git/forseti-security/google/cloud/forseti/services/model/service.py", line 56, in CreateModel
    request.background)
  File "/usr/local/google/home/henryc/git/forseti-security/google/cloud/forseti/services/model/modeller.py", line 54, in CreateModel
    doImport()
  File "/usr/local/google/home/henryc/git/forseti-security/google/cloud/forseti/services/model/modeller.py", line 49, in doImport
    import_runner.run()
  File "/usr/local/google/home/henryc/git/forseti-security/google/cloud/forseti/services/model/importer/importer.py", line 205, in run
    self.session.commit()
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2255, in _flush
    flush_context.execute()
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/google/home/henryc/.virtualenvs/forseti-security/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "build/bdist.linux-x86_64/egg/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "build/bdist.linux-x86_64/egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DataError: (_mysql_exceptions.DataError) (1406, "Data too long for column 'warnings' at row 1") [SQL: u'UPDATE model SET state=%s, message=%s, warnings=%s WHERE model.name = %s'] [parameters: ('PARTIAL_SUCCESS', 1656, 'Role missing permissions: roles/containeranalysis.notes.attacher\nRole missing permissions: roles/resourcemanager.organizationCreator\nRole reference ... (216651 characters truncated) ... projects/stable-device-182522?fields=name&alt=json returned "Required \'compute.projects.get\' permission for \'projects/stable-device-182522\'">\n\n', 'henry4ccc')]```

**Comment by blueandgold** [comment]
@ahoying, can you please take a first look at this?  If this is something for felix/jiyun, can you please take a look?

**Comment by jiyunyao** [comment]
I located the bug which is super weird. https://github.com/GoogleCloudPlatform/forseti-security/blob/5eef92d9d1481467bdb3b50f1d078f564211347a/google/cloud/forseti/services/dao.py#L1585
item.warning_store is not empty when created.
itemx = Model() will also create a new object warning_store is from previous import.
The initialization of warning_store in Model is unstable.

**Comment by ahoying** [comment]
The last bit of the warning message states that the compute.projects.get permission is missing, which means the service account doesn't have the compute.networkViewer role assigned. Can you verify the IAM bindings for the service account on the organization level?

**Comment by jiyunyao** [comment]
+------------------+
| length(warnings) |
+------------------+
|            15163 |
|            15592 |
|            15163 |
|            30586 |
|            15422 |
|            30845 |
|            15422 |
|            30845 |
|            15422 |
|            15422 |
|            30845 |
|            15422 |
|             NULL |
|            15422 |
|            30845 |
|             NULL |
|            15422 |
|            30845 |
+------------------+

I will take a look on the permission and role. But as you can see, when model import from inventory, the warnings do

**Comment by ahoying** [comment]
The inventory warnings are added to the model warnings here:

https://github.com/GoogleCloudPlatform/forseti-security/blob/2.0-dev/google/cloud/forseti/services/model/importer/importer.py#L202

Is that what you are referencing?
